### ISSUE TITLE
ADIF/Cabrillo export

### ISSUE THREAD

**Issue by galengold** [young-amateurs-rc/YARL#3]
Export to common logging formats

**Comment by ntoskrnl4** [comment]
that's what I was already thinking. Only one XML library I've seen so far supports direct conversion of dicts to XML data, mainly because I think you can't store a tag's attributes in a dict.

**Comment by galengold** [comment]
ADIF is generally `<field>value</field>`, right? Then that would map to `{ 'field': 'value' }`. We would need to work around that for adding metadata, etc.

**Comment by ntoskrnl4** [comment]
Yep. The [declxml](http://declxml.readthedocs.io/en/latest/) library can convert XML straight into a (nested) dictionary for ease of use, however, using ElementTree is probably the best solution as it is builtin and rather fast. We can manually convert the data into dictionaries, if we so desire.

**Comment by ntoskrnl4** [comment]
The .adx file generation module has been mostly completed, and it and a small test script are on the `feature/adif-export` branch. Next time I have the time to, I'll fix the build errors and replace the test script with an actual unit test.

I put the file in an "exports" folder so that in the future other forms of data export are possible.

As for performance, on my system, exporting 102400 pieces of data (4096 entries * 25 data points each) took about 1.787 seconds, which is around 17us per data point. That's pretty good but I have not yet tested weaker systems, like a Raspberry Pi. I also plan on doing that when I can.

**Comment by galengold** [comment]
Merged #25. ADIF (ADX) export implemented. Cabrillo export and ADIF import will be separated into other issues.

**Comment by ntoskrnl4** [comment]
Cabrillo format export is now issue #26
